default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password:

development:
  <<: *default
  database: friendlist_development

test:
  <<: *default
  database: friendlist_test

